apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101 
        fsGroup: 101
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:latest 
        ports:
        - containerPort: 8080 
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true 
          capabilities:
            drop:
              - ALL
        # Mount tmp, cache, and run directories as emptyDir volumes to ensure they are writable by the non-root user
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080