apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kehe0014/medmission-platform.git
    targetRevision: develop  # ArgoCD surveille la branche develop pour le dossier dev
    path: gitops/dev        # Dossier source des manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true